# NOME DA APLICAÇÃO
spring.application.name=cofrinho-api

# CONFIGURAÇÕES DE CONEXÃO (JDBC)
# Define o caminho para o banco de dados PostgreSQL.
# O uso da porta padrão 5432 e do banco 'postgres' facilita a configuração do ambiente de desenvolvimento.
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin1531

# CONFIGURAÇÕES DO HIBERNATE / JPA
# ddl-auto=update: Este comando é fundamental. Ele instrui o Hibernate a comparar
# o seu código Java (Classes @Entity) com as tabelas do banco e criar/atualizar
# as colunas automaticamente, sem apagar os dados existentes.
spring.jpa.hibernate.ddl-auto=update

# LOGS E DEBUGGING
# show-sql=true: Exibe no console do IntelliJ todos os comandos SQL que o Spring gera.
# format_sql=true: Organiza o SQL no console para que fique legível para o desenvolvedor.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DIALETO DO BANCO DE DATAS
# Informa ao Hibernate qual "sotaque" de SQL ele deve usar (neste caso, as funções específicas do PostgreSQL).
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect