# NOME DA APLICAÇÃO
spring.application.name=cofrinho-api

# CONFIGURAÇÕES DE CONEXÃO (JDBC)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin1531

# CONFIGURAÇÕES DO HIBERNATE / JPA
spring.jpa.hibernate.ddl-auto=update

# LOGS E DEBUGGING
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DIALETO DO BANCO DE DADOS
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# DEBUG DO SPRING SECURITY
# Força o Hibernate a exibir o SQL gerado e os erros de transação no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.results=DEBUG
logging.level.org.springframework.web=DEBUG